# Generated by Django 3.0.3 on 2020-02-23 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('resumeTitle', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=8, null=True)),
                ('maritalStatus', models.CharField(max_length=8, null=True)),
                ('militaryService', models.CharField(max_length=32, null=True)),
                ('birthDay', models.CharField(max_length=16, null=True)),
                ('birthMonth', models.CharField(max_length=16, null=True)),
                ('birthYear', models.CharField(max_length=16, null=True)),
                ('image', models.ImageField(null=True, upload_to='BasicInfo/images/')),
                ('resumeSummery', models.CharField(max_length=2048, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='resume.Resume')),
            ],
            options={
                'verbose_name': 'BasicInfo',
                'ordering': ('created_time',),
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('socialNetwork', models.CharField(max_length=16, null=True)),
                ('profileID', models.CharField(max_length=64, null=True)),
                ('basic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialNetworks', to='basicInfo.BasicInfo')),
            ],
            options={
                'verbose_name': 'SocialNetwork',
                'ordering': ('created_time',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=256)),
                ('mobile', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('website', models.URLField()),
                ('country', models.CharField(max_length=64, null=True)),
                ('state', models.CharField(max_length=64, null=True)),
                ('city', models.CharField(max_length=64, null=True)),
                ('address', models.CharField(max_length=64, null=True)),
                ('basic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='basicInfo.BasicInfo')),
            ],
            options={
                'verbose_name': 'Contact',
                'ordering': ('created_time',),
            },
        ),
    ]
