# Generated by Django 3.0.3 on 2020-02-23 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicInfo', '0003_remove_basicinfo_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='basicInfo.Contact'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='language',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
