# Generated by Django 3.0.3 on 2020-02-23 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicInfo', '0004_auto_20200223_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='image',
        ),
    ]
