# Generated by Django 3.0.3 on 2020-02-24 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicInfo', '0005_remove_basicinfo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='contact',
        ),
    ]
