# Generated by Django 3.0.3 on 2020-02-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicInfo', '0006_remove_basicinfo_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
