# Generated by Django 3.0.3 on 2020-02-25 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicInfo', '0007_auto_20200224_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicinfo',
            options={},
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='birthDay',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='birthMonth',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='birthYear',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='maritalStatus',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='militaryService',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='resumeSummery',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='resumeTitle',
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='language',
            field=models.CharField(max_length=8),
        ),
        migrations.CreateModel(
            name='BasicInfoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('resumeTitle', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=8, null=True)),
                ('maritalStatus', models.CharField(max_length=8, null=True)),
                ('militaryService', models.CharField(max_length=32, null=True)),
                ('birthDay', models.CharField(max_length=16, null=True)),
                ('birthMonth', models.CharField(max_length=16, null=True)),
                ('birthYear', models.CharField(max_length=16, null=True)),
                ('resumeSummery', models.CharField(max_length=2048, null=True)),
                ('image', models.CharField(max_length=8192, null=True)),
                ('basic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basics', to='basicInfo.BasicInfo')),
            ],
            options={
                'verbose_name': 'BasicInfo',
                'ordering': ('created_time',),
            },
        ),
    ]
