# Generated by Django 3.0.3 on 2020-02-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicInfo', '0010_auto_20200225_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='language',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
