# Generated by Django 3.0.3 on 2020-02-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicInfo', '0011_auto_20200225_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='language',
        ),
    ]
