# Generated by Django 3.0.3 on 2020-02-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicInfo', '0012_remove_basicinfo_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicinfolist',
            options={'ordering': ('created_time',), 'verbose_name': 'BasicInfoList'},
        ),
    ]
