# Generated by Django 3.0.3 on 2020-02-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='currently_studying',
            field=models.BooleanField(null=True),
        ),
    ]
