# Generated by Django 3.0.3 on 2020-02-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20200224_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='currently_studying',
            new_name='currentlyStudying',
        ),
        migrations.RemoveField(
            model_name='education',
            name='address',
        ),
    ]
