# Generated by Django 3.0.3 on 2020-02-24 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20200224_0328'),
        ('education', '0004_auto_20200224_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=64, null=True)),
                ('categoryTitle', models.CharField(max_length=32, null=True)),
                ('employerType', models.CharField(max_length=64, null=True)),
                ('company', models.CharField(max_length=128, null=True)),
                ('employmentType', models.CharField(max_length=64, null=True)),
                ('level', models.CharField(max_length=64, null=True)),
                ('country', models.CharField(max_length=64, null=True)),
                ('state', models.CharField(max_length=64, null=True)),
                ('city', models.CharField(max_length=128, null=True)),
                ('startYear', models.CharField(max_length=16, null=True)),
                ('startMonth', models.CharField(max_length=16, null=True)),
                ('finishYear', models.CharField(max_length=16, null=True)),
                ('finishMonth', models.CharField(max_length=16, null=True)),
                ('present', models.BooleanField(null=True)),
                ('task', models.CharField(max_length=2048, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='resume.Resume')),
            ],
            options={
                'ordering': ('created_time',),
            },
        ),
    ]
