# Generated by Django 3.0.3 on 2020-02-25 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20200225_0405'),
        ('education', '0006_auto_20200224_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to='resume.Resume'),
        ),
    ]
