# Generated by Django 3.0.3 on 2020-02-23 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256, null=True)),
                ('company', models.CharField(max_length=256, null=True)),
                ('linkUrl', models.URLField(null=True)),
                ('year', models.CharField(max_length=16, null=True)),
                ('month', models.CharField(max_length=16, null=True)),
                ('description', models.CharField(max_length=4096, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='resume.Resume')),
            ],
            options={
                'verbose_name': 'Project',
                'ordering': ('created_time',),
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('publishType', models.CharField(max_length=64, null=True)),
                ('title', models.CharField(max_length=256, null=True)),
                ('publisher', models.CharField(max_length=64, null=True)),
                ('linkUrl', models.URLField(null=True)),
                ('year', models.CharField(max_length=16, null=True)),
                ('month', models.CharField(max_length=16, null=True)),
                ('description', models.CharField(max_length=4096, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researches', to='project.Project')),
            ],
            options={
                'verbose_name': 'Research',
                'ordering': ('created_time',),
            },
        ),
    ]
