# Generated by Django 3.0.3 on 2020-02-25 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20200225_0405'),
        ('project', '0002_auto_20200224_0550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='linkUrl',
        ),
        migrations.RemoveField(
            model_name='project',
            name='month',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='year',
        ),
        migrations.AlterField(
            model_name='project',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_project', to='resume.Resume'),
        ),
        migrations.AlterField(
            model_name='research',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researches', to='project.Project'),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256, null=True)),
                ('company', models.CharField(max_length=256, null=True)),
                ('linkUrl', models.URLField(null=True)),
                ('year', models.CharField(max_length=16, null=True)),
                ('month', models.CharField(max_length=16, null=True)),
                ('description', models.CharField(max_length=4096, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.Project')),
            ],
            options={
                'verbose_name': 'Project',
                'ordering': ('created_time',),
            },
        ),
    ]
