# Generated by Django 3.0.3 on 2020-02-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='language',
            field=models.CharField(max_length=8),
        ),
    ]
