# Generated by Django 3.0.3 on 2020-02-24 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('resume', '0004_auto_20200224_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='authentication.User'),
        ),
    ]
