# Generated by Django 3.0.3 on 2020-02-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20200224_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='isActive',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='language',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
