# Generated by Django 3.0.3 on 2020-02-23 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, null=True)),
                ('level', models.IntegerField(null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume.Resume')),
            ],
            options={
                'verbose_name': 'Skill',
                'ordering': ('created_time',),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, null=True)),
                ('readingLevel', models.IntegerField(null=True)),
                ('writingLevel', models.IntegerField(null=True)),
                ('listeningLevel', models.IntegerField(null=True)),
                ('speakingLevel', models.IntegerField(null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='skill.Skill')),
            ],
            options={
                'verbose_name': 'Language',
                'ordering': ('created_time',),
            },
        ),
        migrations.CreateModel(
            name='Honors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256, null=True)),
                ('year', models.CharField(max_length=16, null=True)),
                ('month', models.CharField(max_length=16, null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honors', to='skill.Skill')),
            ],
            options={
                'verbose_name': 'Honor',
                'ordering': ('created_time',),
            },
        ),
        migrations.CreateModel(
            name='AcademicCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=32, null=True)),
                ('title', models.CharField(max_length=256, null=True)),
                ('institute', models.CharField(max_length=256, null=True)),
                ('year', models.CharField(max_length=16, null=True)),
                ('month', models.CharField(max_length=16, null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='skill.Skill')),
            ],
            options={
                'verbose_name': 'Skill',
                'ordering': ('created_time',),
            },
        ),
    ]
