# Generated by Django 3.0.3 on 2020-02-24 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20200224_0550'),
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academiccertificate',
            options={'ordering': ('created_time',), 'verbose_name': 'AcademicCertificate'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.AlterField(
            model_name='skill',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to='resume.Resume'),
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, null=True)),
                ('level', models.IntegerField(null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skill.Skill')),
            ],
            options={
                'verbose_name': 'Skill',
                'ordering': ('created_time',),
            },
        ),
    ]
